version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: api-nestjs-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin**123
      POSTGRES_DB: bd-suarios
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
